apiVersion: k3d.io/v1alpha3
kind: Simple
name: echoserver
servers: 1
agents: 1
image: rancher/k3s:v1.20.15-k3s1
registries:
  create:
    name: k3d-echoserver-registry
    host: "localhost"
ports:
  - port: "30080-30099:30080-30099"
    nodeFilters:
      - "server:0"
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - "server:*"
