apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kov
resources:
  - https://codeberg.org/hjacobs/kube-ops-view/deploy
  - namespace.yaml
patches:
  - target:
      kind: Deployment
      name: kube-ops-view
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Service
      name: kube-ops-view
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: replace
        path: /spec/ports
        value:
          - port: 80
            targetPort: 8080
            nodePort: 30099
