apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - name: echoserver
          image: echoserver
          command: ["/build/linux/echoserver"]
          args:
            - --banner=false
            - --host=0.0.0.0
            - --liveness-path=/build/linux/echoserver-live
            - --log-level=debug
          ports:
            - containerPort: 8080
      livenessProbe:
        exec:
          command:
            - /build/linux/echoserver
            - live
          initialDelaySeconds: 2
          periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /health
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  selector:
    app: echoserver
  ports:
    - port: 8080
      nodePort: 30080
  type: NodePort
